### ISSUE TITLE
onBackPressed和onKeyDown有冲突吧?

### ISSUE THREAD

**Issue by SheepYang1993** [HotBitmapGG/MoeQuest#2]
把onBackPressed里的判断写到onKeyDown里面?

**Comment by HotBitmapGG** [comment]
具体哪个位置的问题啊,

**Comment by HotBitmapGG** [comment]
ok，看到了，那段代码onBackPressed的代码设置Nav菜单打开的，忘记去掉了，已删除掉了，谢谢提醒 @SheepYang1993
