### ISSUE TITLE
API 19 状态栏瑕疵

### ISSUE THREAD

**Issue by forJrking** [HotBitmapGG/MoeQuest#5]
4.4 小米手机上打开侧滑菜单右上角有点不和谐，建议：做透明状态栏，可以参考我这个 [示例](https://github.com/forJrking/StatusBarUtils)

**Comment by HotBitmapGG** [comment]
好的，谢谢，因为我木有4.4的手机，手上就一台N6，所以适配问题肯定是存在的。

**Comment by HotBitmapGG** [comment]
已修改
